#!/usr/bin/env python3
"""
Auto-generate the reference half of the agent pack.

`AGENTS.md`, `SKILL.md` and three of the five `references/` files are
hand-written: they carry judgment about what an agent gets wrong, which no
registry knows. `references/annotation-types.md` and `references/config-keys.md`
are the opposite -- field lists and key tables that must match what the server
enforces, so they are generated and CI fails when they drift.

The hand-written references (`designing-a-task.md`, `asking-the-experimenter.md`,
`building-the-ui.md`) are never written by this script. They are checked instead:
`tests/test_skill_sync.py` asserts every annotation type, display type
and config key they name is real.

Also mirrors AGENTS.md into the docs site, so the pack has a public URL for
anyone who has not installed the plugin.

Usage:
    python scripts/generate_references.py
    python scripts/generate_references.py --check   # exit 1 if stale
"""

import argparse
import os
import sys

from potato.server_utils.config_key_docs import UNSET, iter_key_docs
from potato.server_utils.displays import display_registry
from potato.server_utils.schema_examples import example_scheme_for, example_source_for
from potato.server_utils.schemas.registry import (
    UNIVERSAL_OPTIONAL_FIELDS,
    UNIVERSAL_REQUIRED_FIELDS,
    schema_registry,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(ROOT, "skills", "potato-tasks")
AGENTS_MD = os.path.join(ROOT, "AGENTS.md")
REFERENCES = os.path.join(PACK, "references")

# Public copy, so an agent can be pointed at a URL rather than an install.
DOCS_MIRROR = os.path.join(ROOT, "docs", "agents-md.md")

HEADER = (
    "<!-- Generated by scripts/generate_references.py. Do not edit by hand. -->\n\n"
)


def _yaml_block(scheme: dict) -> str:
    import yaml

    body = yaml.safe_dump(
        [scheme], sort_keys=False, default_flow_style=False, allow_unicode=True
    )
    return "```yaml\n" + body.rstrip() + "\n```"


def render_annotation_types() -> str:
    lines = [
        HEADER.rstrip("\n"),
        "",
        "# Annotation types",
        "",
        f"Potato has {len(schema_registry.get_supported_types())} annotation types. "
        "Set one as `annotation_type` on each entry in `annotation_schemes`.",
        "",
        "Every type also accepts these, regardless of which one you pick:",
        "",
        "- Required: " + ", ".join(f"`{f}`" for f in sorted(UNIVERSAL_REQUIRED_FIELDS)),
        "- Optional: " + ", ".join(f"`{f}`" for f in sorted(UNIVERSAL_OPTIONAL_FIELDS)),
        "",
        "The examples below are lifted from configs in `examples/` that use each "
        "type, so they are known to run.",
        "",
        "## Index",
        "",
    ]

    schemas = schema_registry.list_schemas()
    for schema in schemas:
        anchor = schema["name"].replace("_", "-")
        lines.append(f"- [`{schema['name']}`](#{anchor}) — {schema['description']}")
    lines.append("")

    for schema in schemas:
        name = schema["name"]
        lines.append(f"## {name}")
        lines.append("")
        if schema["description"]:
            lines.append(schema["description"])
            lines.append("")

        required = [
            f for f in sorted(schema["required_fields"])
            if f not in ("name", "description")
        ]
        lines.append(
            "**Required:** "
            + (", ".join(f"`{f}`" for f in required) if required else
               "nothing beyond `name` and `description`")
        )
        optional = sorted(schema["optional_fields"])
        lines.append("")
        lines.append(
            "**Optional:** "
            + (", ".join(f"`{f}`" for f in optional) if optional else "none")
        )
        lines.append("")

        example = example_scheme_for(name)
        if example:
            lines.append(_yaml_block(example))
            source = example_source_for(name)
            if source:
                lines.append("")
                lines.append(f"From `{source}`.")
        else:
            lines.append("_No example config ships with this type._")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_config_keys() -> str:
    by_category = {}
    for path, doc in iter_key_docs():
        if "." in path:
            continue
        by_category.setdefault(doc.category, []).append((path, doc))

    documented = sum(len(v) for v in by_category.values())
    lines = [
        HEADER.rstrip("\n"),
        "",
        "# Config keys",
        "",
        f"The {documented} documented top-level keys. The complete list of "
        "recognized keys, including nested ones, is in "
        "`docs/configuration/config_reference.md`.",
        "",
        "Unrecognized keys only produce a warning, so a typo silently disables "
        "whatever you meant to switch on. Run `potato validate --strict` to make "
        "that a failure.",
        "",
    ]

    for category in sorted(by_category):
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Key | Type | Required | Default | Description |")
        lines.append("|-----|------|----------|---------|-------------|")
        for path, doc in sorted(by_category[category]):
            default = "" if doc.default is UNSET else f"`{doc.default!r}`"
            if isinstance(doc.default, str) and doc.default is not UNSET:
                default = '`""`' if doc.default == "" else f"`{doc.default}`"
            summary = doc.summary.replace("|", r"\|")
            required = "Yes" if doc.required else ""
            lines.append(
                f"| `{path}` | {doc.type} | {required} | {default} | {summary} |"
            )
        lines.append("")

    lines.append("## Display types")
    lines.append("")
    lines.append(
        f"`instance_display.fields[].type` accepts "
        f"{len(display_registry.get_supported_types())} values:"
    )
    lines.append("")
    lines.append("| Type | Description | Span target |")
    lines.append("|------|-------------|-------------|")
    for display in display_registry.list_displays():
        span = "yes" if display.get("supports_span_target") else ""
        description = (display.get("description") or "").replace("|", r"\|")
        lines.append(f"| `{display['name']}` | {description} | {span} |")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


#: How to take the skill somewhere Potato is not installed. Lives here rather
#: than in AGENTS.md because it is about distributing the pack, not about
#: building a task -- an agent reading AGENTS.md inside a project does not need
#: it.
REUSE_SECTION = """\
## Installing the skill

```
/plugin marketplace add davidjurgens/potato-skill
/plugin install potato-tasks@potato
```

The skill is a plain directory, so it also travels:

```bash
python scripts/package_skill.py
```

builds `dist/potato-tasks/` -- `SKILL.md`, the references, and the six
executable helpers -- and `dist/potato-tasks.zip`. One build, three destinations:

| Where | How |
|---|---|
| Claude Code, every project on the machine | `cp -r dist/potato-tasks ~/.claude/skills/`, or `--install-personal` |
| Claude Agent SDK | Point the SDK's skill directory at `dist/`; it loads the skill the same way Claude Code does |
| Claude API | Upload `dist/potato-tasks.zip` as a skill, then name it on the request. The endpoint is in beta -- check Anthropic's Agent Skills documentation for the current call |

The scripts in the bundle drive the `potato` command and import Potato's
registries, so wherever the skill runs, Potato has to be installed in the
environment running the commands. `SKILL.md` opens by checking exactly that.

"""


def render_docs_mirror() -> str:
    """AGENTS.md as a docs page, so the pack has a URL."""
    with open(AGENTS_MD, "r", encoding="utf-8") as f:
        body = f.read()

    body = body.replace("# Working on a Potato annotation task", "", 1).lstrip()

    return (
        "<!-- Generated by scripts/generate_references.py from "
        "AGENTS.md. Do not edit by hand. -->\n\n"
        "# Agent Instructions\n\n"
        "Claude Code, Codex and Cursor all read `AGENTS.md`, so it needs no "
        "install step. Copy it into the project you are working in. The text "
        "below is that file.\n\n"
        + REUSE_SECTION
        + "---\n\n"
        + body
    )


def render_config_keys_nested() -> str:
    """The sub-key level, which `config-keys.md` stops short of.

    Sub-keys are where a feature is actually configured, and where a typo is
    most likely to go unnoticed: several blocks are not checked at all, so
    `--strict` cannot help there.
    """
    from potato.server_utils.config_module import KNOWN_CONFIG_KEYS

    by_parent = {}
    for path, doc in iter_key_docs():
        if "." not in path:
            continue
        parent, _, leaf = path.partition(".")
        by_parent.setdefault(parent, []).append((leaf, doc))

    tops = {path: doc for path, doc in iter_key_docs() if "." not in path}
    documented = sum(len(v) for v in by_parent.values())

    # A block whose KNOWN_CONFIG_KEYS entry is None accepts anything inside it,
    # so `--strict` cannot catch a misspelled sub-key there.
    unchecked = sorted(
        name for name, allowed in KNOWN_CONFIG_KEYS.items()
        if allowed is None
        and not name.startswith("_")
        and (name in by_parent or tops.get(name, None) is not None
             and tops[name].type in ("object", "array"))
    )

    lines = [
        HEADER.rstrip("\n"),
        "",
        "# Nested config keys",
        "",
        f"`config-keys.md` lists the top-level keys and stops there. The "
        f"{documented} keys below are the documented **sub-keys** -- the level "
        "where a feature is actually configured.",
        "",
        "`get_key_doc(\"attention_checks.frequency\")` returns any of these "
        "individually.",
        "",
        "Read this before configuring a block. Guessing a plausible sub-key name "
        "and running `potato validate --strict` works for most blocks, but not "
        "for the ones listed at the end, where a typo is silent.",
        "",
    ]

    for parent in sorted(by_parent):
        lines.append(f"## `{parent}`")
        lines.append("")
        parent_doc = tops.get(parent)
        if parent_doc is not None:
            lines.append(parent_doc.summary)
            lines.append("")
        lines.append("| Key | Type | Default | Description |")
        lines.append("|---|---|---|---|")
        for leaf, doc in sorted(by_parent[parent]):
            default = "" if doc.default is UNSET else f"`{doc.default!r}`"
            if isinstance(doc.default, str) and doc.default is not UNSET:
                default = '`""`' if doc.default == "" else f"`{doc.default}`"
            summary = doc.summary.replace("|", r"\|")
            lines.append(f"| `{leaf}` | {doc.type} | {default} | {summary} |")
        lines.append("")

    lines.append("## Blocks whose sub-keys are not checked")
    lines.append("")
    lines.append(
        "`potato validate --strict` fails on an unrecognized sub-key in most "
        "blocks. In these it accepts anything, so a misspelled sub-key is "
        "silent and the feature is simply off:"
    )
    lines.append("")
    for name in unchecked:
        lines.append(f"- `{name}.*`")
    lines.append("")
    lines.append(
        "Checking is also at most two levels deep everywhere else: "
        "`training.feedback` is checked, `training.feedback.anything` is not. "
        "Entries inside `annotation_schemes` and `instance_display.fields` are "
        "not checked either, which is why `key_binding` in place of `key_value` "
        "validates clean and does nothing."
    )
    lines.append("")
    return "\n".join(lines)


#: Hand-written references mirrored into the docs site, so the guidance has a
#: public URL for people who have not installed the plugin. Byte-identical
#: to the packaged copy apart from a generated header.
MIRRORED_REFERENCES = {
    "designing-a-task.md": (
        "Designing an Annotation Task",
        "The decisions behind a task, before any YAML gets written.",
    ),
    "asking-the-experimenter.md": (
        "What to Confirm With the Researcher",
        "Which design choices to make yourself and which to hand back.",
    ),
    "interviewing.md": (
        "Interviewing the Researcher",
        "The multiple-choice question bank for a task described from scratch.",
    ),
    "building-the-ui.md": (
        "Building the Annotation Interface",
        "`instance_display`, the display types, and what a screenshot can prove.",
    ),
    "evaluating-the-ui.md": (
        "Evaluating and Iterating on the Interface",
        "How to judge a rendered annotation page and what to change.",
    ),
    "modalities.md": (
        "Images, Video, Audio and 3D",
        "Routing a medium to its display type, its scheme, and its quirks.",
    ),
    "agent-traces.md": (
        "Agent Traces and Agent Evaluation",
        "The trace displays, the twenty evaluation schemes, and how they bind.",
    ),
    "finding-a-design.md": (
        "Starting From a Published Design",
        "The Potato Showcase, and what to change before reusing a design.",
    ),
    "importing-existing-work.md": (
        "Importing Existing Annotations, Transcripts and Corpora",
        "What to do when the researcher already has annotated data.",
    ),
    "getting-the-data-out.md": (
        "Getting the Annotations Out",
        "The export formats, what a CSV holds, and where consent answers go.",
    ),
    "after-annotators-start.md": (
        "After Annotators Start",
        "Watching a live study, what is still safe to change, and what is not.",
    ),
    "writing-guidelines.md": (
        "Writing the Annotation Guidelines",
        "Label definitions, tie-break rules and the codebook an annotator reads.",
    ),
    "interrogating-potato.md": (
        "Interrogating Potato",
        "Recovering an undocumented config block from the validator and the log.",
    ),
    "recording-decisions.md": (
        "Recording Design Decisions",
        "`DESIGN.md`, `QUESTIONS.md`, and estimating what a task will cost.",
    ),
    "phases-and-pages.md": (
        "Phases and Pages",
        "Consent, instructions, training, surveys, and the order they run in.",
    ),
    "quality-control.md": (
        "Attention Checks and Gold Standards",
        "The quality-control ladder, and what each rung costs.",
    ),
    "assignment-and-agreement.md": (
        "Assignment and Agreement",
        "Who annotates what, and which agreement measure follows from it.",
    ),
    "modes-and-subsystems.md": (
        "Modes and Subsystems",
        "The whole-task modes a brief can be asking for without naming.",
    ),
    "data-and-access.md": (
        "Data Files and Admin Access",
        "Input formats, side files, and reading results back out.",
    ),
    "running-a-task.md": (
        "Running a Task",
        "Booting a server, reading the startup log, and handing it over.",
    ),
    "troubleshooting.md": (
        "When a Task Misbehaves",
        "Symptoms that validate clean and then do something else.",
    ),
    "worked-example.md": (
        "A Worked Example",
        "One complete task, annotated, and what to change first.",
    ),
    "deploying.md": (
        "Deploying a Task",
        "Putting a task somewhere annotators can reach it.",
    ),
}


def _render_reference_mirror(filename: str, title: str, blurb: str) -> str:
    with open(os.path.join(REFERENCES, filename), "r", encoding="utf-8") as f:
        body = f.read()
    # Drop the reference's own H1; the docs page supplies the title.
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        body = "\n".join(lines[1:]).lstrip("\n")
    return (
        f"<!-- Generated by scripts/generate_references.py from "
        f"skills/potato-tasks/references/{filename}. Do not edit by hand. -->\n\n"
        f"# {title}\n\n"
        f"{blurb} It ships with the `potato-tasks` skill:\n\n"
        "```\n"
        "/plugin marketplace add davidjurgens/potato-skill\n"
        "/plugin install potato-tasks@potato\n"
        "```\n\n"
        "---\n\n"
        + body
    )


OUTPUTS = {
    os.path.join(REFERENCES, "annotation-types.md"): render_annotation_types,
    os.path.join(REFERENCES, "config-keys.md"): render_config_keys,
    os.path.join(REFERENCES, "config-keys-nested.md"): render_config_keys_nested,
    DOCS_MIRROR: render_docs_mirror,
}

for _name, (_title, _blurb) in MIRRORED_REFERENCES.items():
    OUTPUTS[os.path.join(ROOT, "docs", _name)] = (
        lambda n=_name, t=_title, b=_blurb: _render_reference_mirror(n, t, b)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Verify without writing"
    )
    args = parser.parse_args()

    stale = []
    for path, render in OUTPUTS.items():
        payload = render()
        if args.check:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    current = f.read()
            except OSError:
                stale.append(f"{os.path.relpath(path, ROOT)} (missing)")
                continue
            if current != payload:
                stale.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(payload)
            print(f"Wrote {os.path.relpath(path, ROOT)}")

    if args.check:
        if stale:
            print(
                "References are stale: "
                + ", ".join(stale)
                + "\nRegenerate with: python scripts/generate_references.py",
                file=sys.stderr,
            )
            return 1
        print("References are current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
