"""
MkDocs hooks for the published site: the machine-readable copies of it.

Search engines read the HTML. Answer engines and agents do better with the
markdown, so the build also writes, next to the HTML:

- `<page>.md` for every page, the source with its front matter and generated
  header removed;
- `llms.txt`, an index of those files in the llmstxt.org format, in nav order,
  each with the page's `summary` (or `description` where it has none);
- `llms-full.txt`, every page concatenated.

All three are derived during the build from the pages it rendered, so none of
them is committed and none can drift. The hook also puts the plugin version
from `.claude-plugin/plugin.json` into `config.extra`, for the structured data
in `overrides/main.html`.
"""

import json
import os
import re

_PAGES = {}
_ORDER = []

_GENERATED_HEADER = re.compile(r"\A\s*<!-- Generated by .*? -->\n+", re.S)


def on_config(config):
    root = os.path.dirname(config.config_file_path)
    with open(os.path.join(root, ".claude-plugin", "plugin.json"),
              encoding="utf-8") as f:
        config.extra["plugin_version"] = json.load(f)["version"]
    _PAGES.clear()
    _ORDER.clear()
    return config


def on_nav(nav, config, files):
    _ORDER.extend(page.file.src_uri for page in nav.pages)
    return nav


def on_page_markdown(markdown, page, config, files):
    _PAGES[page.file.src_uri] = {
        "title": page.meta.get("title") or page.title,
        "description": page.meta.get("summary") or page.meta.get("description", ""),
        "url": page.canonical_url,
        "markdown": _GENERATED_HEADER.sub("", markdown).strip() + "\n",
    }
    return markdown


def on_post_build(config):
    site = config.site_url.rstrip("/") + "/"
    out = config.site_dir
    ordered = [src for src in _ORDER if src in _PAGES]
    ordered += sorted(src for src in _PAGES if src not in _ORDER)

    for src in ordered:
        with open(os.path.join(out, src), "w", encoding="utf-8") as f:
            f.write(_PAGES[src]["markdown"])

    def entry(src):
        page = _PAGES[src]
        line = f"- [{page['title']}]({site}{src})"
        return line + (f": {page['description']}" if page["description"] else "")

    lines = [f"# {config.site_name}", ""]
    if config.site_description:
        lines += [f"> {config.site_description}", ""]
    lines += [
        "These pages are the reference material the skill loads while an "
        "agent builds a Potato annotation task. Each link below is a page's "
        "markdown source; the HTML version is the same path without `.md`.",
        "",
        f"- Announcement: {config.extra['announcement_url']}",
        f"- Source code: {config.repo_url}",
        f"- Potato: {config.extra['potato_url']}",
        "",
        "## Pages",
        "",
    ]
    lines += [entry(src) for src in ordered if src != "index.md"]
    lines += ["", "## Optional", ""]
    if "index.md" in _PAGES:
        lines.append(entry("index.md"))
    lines.append(f"- [Every page in one file]({site}llms-full.txt)")
    with open(os.path.join(out, "llms.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    with open(os.path.join(out, "llms-full.txt"), "w", encoding="utf-8") as f:
        for src in ordered:
            f.write(f"<!-- {_PAGES[src]['url']} -->\n\n")
            f.write(_PAGES[src]["markdown"])
            f.write("\n")
